export interface Conference {
  id: string;
  name: string;
  shortName: string;
}

export interface NCASchool {
  name: string;
  staffDirectoryUrl: string;
}

export interface NCAAConferenceWithSchools {
  id: string;
  name: string;
  shortName: string;
  schools: NCASchool[];
}

export const ncaaConferences: Conference[] = [
  { id: 'ACC', name: 'Atlantic Coast Conference', shortName: 'ACC' },
  { id: 'Big12', name: 'Big 12 Conference', shortName: 'Big 12' },
  { id: 'BigTen', name: 'Big Ten Conference', shortName: 'Big Ten' },
  { id: 'SEC', name: 'Southeastern Conference', shortName: 'SEC' },
  { id: 'Pac12', name: 'Pac-12 Conference', shortName: 'Pac-12' },
  { id: 'AAC', name: 'American Athletic Conference', shortName: 'AAC' },
  { id: 'MWC', name: 'Mountain West Conference', shortName: 'MWC' },
  { id: 'SunBelt', name: 'Sun Belt Conference', shortName: 'Sun Belt' },
  { id: 'MAC', name: 'Mid-American Conference', shortName: 'MAC' },
  { id: 'CUSA', name: 'Conference USA', shortName: 'CUSA' },
  { id: 'IvyLeague', name: 'Ivy League', shortName: 'Ivy' },
  { id: 'A10', name: 'Atlantic 10 Conference', shortName: 'A-10' },
  { id: 'WCC', name: 'West Coast Conference', shortName: 'WCC' },
  { id: 'MEAC', name: 'Mid-Eastern Athletic Conference', shortName: 'MEAC' },
  { id: 'SWAC', name: 'Southwestern Athletic Conference', shortName: 'SWAC' },
  { id: 'CAA', name: 'Colonial Athletic Association', shortName: 'CAA' },
  { id: 'Horizon', name: 'Horizon League', shortName: 'Horizon' },
  { id: 'MVC', name: 'Missouri Valley Conference', shortName: 'MVC' },
  { id: 'Summit', name: 'Summit League', shortName: 'Summit' },
  { id: 'BigSky', name: 'Big Sky Conference', shortName: 'Big Sky' },
];

export const ncaaConferencesWithSchools: NCAAConferenceWithSchools[] = [
  {
    id: "SEC",
    name: "Southeastern Conference",
    shortName: "SEC",
    schools: [
      { name: "Alabama", staffDirectoryUrl: "https://rolltide.com/staff-directory" },
      { name: "Arkansas", staffDirectoryUrl: "https://arkansasrazorbacks.com/staff-directory" },
      { name: "Auburn", staffDirectoryUrl: "https://auburntigers.com/staff-directory" },
      { name: "Florida", staffDirectoryUrl: "https://floridagators.com/staff-directory" },
      { name: "Georgia", staffDirectoryUrl: "https://georgiadogs.com/staff-directory" },
      { name: "Kentucky", staffDirectoryUrl: "https://ukathletics.com/staff-directory" },
      { name: "LSU", staffDirectoryUrl: "https://lsusports.net/staff-directory" },
      { name: "Mississippi State", staffDirectoryUrl: "https://hailstate.com/staff-directory" },
      { name: "Missouri", staffDirectoryUrl: "https://mutigers.com/staff-directory" },
      { name: "Ole Miss", staffDirectoryUrl: "https://olemisssports.com/staff-directory" },
      { name: "South Carolina", staffDirectoryUrl: "https://gamecocksonline.com/staff-directory" },
      { name: "Tennessee", staffDirectoryUrl: "https://utsports.com/staff-directory" },
      { name: "Texas A&M", staffDirectoryUrl: "https://12thman.com/staff-directory" },
      { name: "Vanderbilt", staffDirectoryUrl: "https://vucommodores.com/staff-directory" },
    ],
  },
  {
    id: "BigTen",
    name: "Big Ten Conference",
    shortName: "Big Ten",
    schools: [
      { name: "Illinois", staffDirectoryUrl: "https://fightingillini.com/staff-directory" },
      { name: "Indiana", staffDirectoryUrl: "https://iuhoosiers.com/staff-directory" },
      { name: "Iowa", staffDirectoryUrl: "https://hawkeyesports.com/staff-directory" },
      { name: "Maryland", staffDirectoryUrl: "https://umterps.com/staff-directory" },
      { name: "Michigan", staffDirectoryUrl: "https://mgoblue.com/sports/2017/6/16/staff-directory-alpha" },
      { name: "Michigan State", staffDirectoryUrl: "https://msuspartans.com/staff-directory" },
      { name: "Minnesota", staffDirectoryUrl: "https://gophersports.com/staff-directory" },
      { name: "Nebraska", staffDirectoryUrl: "https://huskers.com/staff-directory" },
      { name: "Northwestern", staffDirectoryUrl: "https://nusports.com/staff-directory" },
      { name: "Ohio State", staffDirectoryUrl: "https://ohiostatebuckeyes.com/staff-directory" },
      { name: "Penn State", staffDirectoryUrl: "https://gopsusports.com/staff-directory" },
      { name: "Purdue", staffDirectoryUrl: "https://purduesports.com/staff-directory" },
      { name: "Rutgers", staffDirectoryUrl: "https://scarletknights.com/staff-directory" },
      { name: "Wisconsin", staffDirectoryUrl: "https://uwbadgers.com/staff-directory" },
    ],
  },
  {
    id: "ACC",
    name: "Atlantic Coast Conference",
    shortName: "ACC",
    schools: [
      { name: "Boston College", staffDirectoryUrl: "https://bceagles.com/staff-directory" },
      { name: "Clemson", staffDirectoryUrl: "https://clemsontigers.com/staff-directory" },
      { name: "Duke", staffDirectoryUrl: "https://goduke.com/staff-directory" },
      { name: "Florida State", staffDirectoryUrl: "https://seminoles.com/staff-directory" },
      { name: "Georgia Tech", staffDirectoryUrl: "https://ramblinwreck.com/staff-directory" },
      { name: "Louisville", staffDirectoryUrl: "https://gocards.com/staff-directory" },
      { name: "Miami", staffDirectoryUrl: "https://hurricanesports.com/staff-directory" },
      { name: "NC State", staffDirectoryUrl: "https://gopack.com/staff-directory" },
      { name: "North Carolina", staffDirectoryUrl: "https://goheels.com/staff-directory" },
      { name: "Notre Dame", staffDirectoryUrl: "https://fightingirish.com/staff-directory" },
      { name: "Pitt", staffDirectoryUrl: "https://pittsburghpanthers.com/staff-directory" },
      { name: "Syracuse", staffDirectoryUrl: "https://cuse.com/staff-directory" },
      { name: "Virginia", staffDirectoryUrl: "https://virginiasports.com/staff-directory" },
      { name: "Virginia Tech", staffDirectoryUrl: "https://hokiesports.com/staff-directory" },
      { name: "Wake Forest", staffDirectoryUrl: "https://wakeforestsports.com/staff-directory" },
    ],
  },
  {
    id: "Pac12",
    name: "Pac-12 Conference",
    shortName: "Pac-12",
    schools: [
      { name: "Arizona", staffDirectoryUrl: "https://arizonawildcats.com/staff-directory" },
      { name: "Arizona State", staffDirectoryUrl: "https://thesundevils.com/staff-directory" },
      { name: "California", staffDirectoryUrl: "https://calbears.com/staff-directory" },
      { name: "Colorado", staffDirectoryUrl: "https://cubuffs.com/staff-directory" },
      { name: "Oregon", staffDirectoryUrl: "https://goducks.com/staff-directory" },
      { name: "Oregon State", staffDirectoryUrl: "https://osubeavers.com/staff-directory" },
      { name: "Stanford", staffDirectoryUrl: "https://gostanford.com/staff-directory" },
      { name: "UCLA", staffDirectoryUrl: "https://uclabruins.com/staff-directory" },
      { name: "USC", staffDirectoryUrl: "https://usctrojans.com/staff-directory" },
      { name: "Utah", staffDirectoryUrl: "https://utahutes.com/staff-directory" },
      { name: "Washington", staffDirectoryUrl: "https://gohuskies.com/staff-directory" },
      { name: "Washington State", staffDirectoryUrl: "https://wsucougars.com/staff-directory" },
    ],
  },
  {
    id: "Big12",
    name: "Big 12 Conference",
    shortName: "Big 12",
    schools: [
      { name: "Baylor", staffDirectoryUrl: "https://baylorbears.com/staff-directory" },
      { name: "BYU", staffDirectoryUrl: "https://byucougars.com/staff-directory" },
      { name: "Cincinnati", staffDirectoryUrl: "https://gobearcats.com/staff-directory" },
      { name: "Houston", staffDirectoryUrl: "https://uhcougars.com/staff-directory" },
      { name: "Iowa State", staffDirectoryUrl: "https://cyclones.com/staff-directory" },
      { name: "Kansas", staffDirectoryUrl: "https://kuathletics.com/staff-directory" },
      { name: "Kansas State", staffDirectoryUrl: "https://kstatesports.com/staff-directory" },
      { name: "Oklahoma State", staffDirectoryUrl: "https://okstate.com/staff-directory" },
      { name: "TCU", staffDirectoryUrl: "https://gofrogs.com/staff-directory" },
      { name: "Texas Tech", staffDirectoryUrl: "https://texastech.com/staff-directory" },
      { name: "UCF", staffDirectoryUrl: "https://ucfknights.com/staff-directory" },
      { name: "West Virginia", staffDirectoryUrl: "https://wvusports.com/staff-directory" },
    ],
  },
  {
    id: "IvyLeague",
    name: "Ivy League",
    shortName: "Ivy",
    schools: [
      { name: "Brown", staffDirectoryUrl: "https://brownbears.com/staff-directory" },
      { name: "Columbia", staffDirectoryUrl: "https://gocolumbialions.com/staff-directory" },
      { name: "Cornell", staffDirectoryUrl: "https://cornellbigred.com/staff-directory" },
      { name: "Dartmouth", staffDirectoryUrl: "https://dartmouthsports.com/staff-directory" },
      { name: "Harvard", staffDirectoryUrl: "https://gocrimson.com/staff-directory" },
      { name: "Penn", staffDirectoryUrl: "https://pennathletics.com/staff-directory" },
      { name: "Princeton", staffDirectoryUrl: "https://goprincetontigers.com/staff-directory" },
      { name: "Yale", staffDirectoryUrl: "https://yalebulldogs.com/staff-directory" },
    ],
  },
  {
    id: "CAA",
    name: "Colonial Athletic Association",
    shortName: "CAA",
    schools: [
      { name: "Campbell", staffDirectoryUrl: "https://gocamels.com/staff-directory" },
      { name: "Charleston", staffDirectoryUrl: "https://cofcsports.com/staff-directory" },
      { name: "Delaware", staffDirectoryUrl: "https://bluehens.com/staff-directory" },
      { name: "Drexel", staffDirectoryUrl: "https://drexeldragons.com/staff-directory" },
      { name: "Elon", staffDirectoryUrl: "https://elonphoenix.com/staff-directory" },
      { name: "Hampton", staffDirectoryUrl: "https://hamptonpirates.com/staff-directory" },
      { name: "Hofstra", staffDirectoryUrl: "https://gohofstra.com/staff-directory" },
      { name: "Monmouth", staffDirectoryUrl: "https://monmouthhawks.com/staff-directory" },
      { name: "North Carolina A&T", staffDirectoryUrl: "https://ncataggies.com/staff-directory" },
      { name: "Northeastern", staffDirectoryUrl: "https://gonu.com/staff-directory" },
      { name: "Stony Brook", staffDirectoryUrl: "https://stonybrookathletics.com/staff-directory" },
      { name: "Towson", staffDirectoryUrl: "https://towsontigers.com/staff-directory" },
      { name: "UNC Wilmington", staffDirectoryUrl: "https://uncwsports.com/staff-directory" },
      { name: "William & Mary", staffDirectoryUrl: "https://tribeathletics.com/staff-directory" },
    ],
  },
  {
    id: "AAC",
    name: "American Athletic Conference",
    shortName: "AAC",
    schools: [
      { name: "Charlotte", staffDirectoryUrl: "https://charlotte49ers.com/staff-directory" },
      { name: "East Carolina", staffDirectoryUrl: "https://ecupirates.com/staff-directory" },
      { name: "FAU", staffDirectoryUrl: "https://fausports.com/staff-directory" },
      { name: "Memphis", staffDirectoryUrl: "https://gotigersgo.com/staff-directory" },
      { name: "Navy", staffDirectoryUrl: "https://navysports.com/staff-directory" },
      { name: "North Texas", staffDirectoryUrl: "https://meangreensports.com/staff-directory" },
      { name: "Rice", staffDirectoryUrl: "https://riceowls.com/staff-directory" },
      { name: "South Florida", staffDirectoryUrl: "https://gousfbulls.com/staff-directory" },
      { name: "Temple", staffDirectoryUrl: "https://owlsports.com/staff-directory" },
      { name: "Tulane", staffDirectoryUrl: "https://tulanegreenwave.com/staff-directory" },
      { name: "Tulsa", staffDirectoryUrl: "https://tulsahurricane.com/staff-directory" },
      { name: "UAB", staffDirectoryUrl: "https://uabsports.com/staff-directory" },
      { name: "UTSA", staffDirectoryUrl: "https://goutsa.com/staff-directory" },
      { name: "Wichita State", staffDirectoryUrl: "https://goshockers.com/staff-directory" },
    ],
  },
  {
    id: "MWC",
    name: "Mountain West Conference",
    shortName: "MWC",
    schools: [
      { name: "Air Force", staffDirectoryUrl: "https://goairforcefalcons.com/staff-directory" },
      { name: "Boise State", staffDirectoryUrl: "https://broncosports.com/staff-directory" },
      { name: "Colorado State", staffDirectoryUrl: "https://csurams.com/staff-directory" },
      { name: "Fresno State", staffDirectoryUrl: "https://gobulldogs.com/staff-directory" },
      { name: "Hawaii", staffDirectoryUrl: "https://hawaiiathletics.com/staff-directory" },
      { name: "Nevada", staffDirectoryUrl: "https://nevadawolfpack.com/staff-directory" },
      { name: "New Mexico", staffDirectoryUrl: "https://golobos.com/staff-directory" },
      { name: "San Diego State", staffDirectoryUrl: "https://goaztecs.com/staff-directory" },
      { name: "San Jose State", staffDirectoryUrl: "https://sjsuspartans.com/staff-directory" },
      { name: "UNLV", staffDirectoryUrl: "https://unlvrebels.com/staff-directory" },
      { name: "Utah State", staffDirectoryUrl: "https://utahstateaggies.com/staff-directory" },
      { name: "Wyoming", staffDirectoryUrl: "https://gowyo.com/staff-directory" },
    ],
  },
  {
    id: "SunBelt",
    name: "Sun Belt Conference",
    shortName: "Sun Belt",
    schools: [
      { name: "Appalachian State", staffDirectoryUrl: "https://appstatesports.com/staff-directory" },
      { name: "Arkansas State", staffDirectoryUrl: "https://astateredwolves.com/staff-directory" },
      { name: "Coastal Carolina", staffDirectoryUrl: "https://goccusports.com/staff-directory" },
      { name: "Georgia State", staffDirectoryUrl: "https://georgiastatesports.com/staff-directory" },
      { name: "Georgia Southern", staffDirectoryUrl: "https://gseagles.com/staff-directory" },
      { name: "James Madison", staffDirectoryUrl: "https://jmusports.com/staff-directory" },
      { name: "Louisiana", staffDirectoryUrl: "https://ragincajuns.com/staff-directory" },
      { name: "UL Monroe", staffDirectoryUrl: "https://ulmwarhawks.com/staff-directory" },
      { name: "Marshall", staffDirectoryUrl: "https://herdzone.com/staff-directory" },
      { name: "Old Dominion", staffDirectoryUrl: "https://odusports.com/staff-directory" },
      { name: "South Alabama", staffDirectoryUrl: "https://usajaguars.com/staff-directory" },
      { name: "Southern Miss", staffDirectoryUrl: "https://southernmiss.com/staff-directory" },
      { name: "Texas State", staffDirectoryUrl: "https://txstatebobcats.com/staff-directory" },
      { name: "Troy", staffDirectoryUrl: "https://troytrojans.com/staff-directory" },
    ],
  },
  {
    id: "MAC",
    name: "Mid-American Conference",
    shortName: "MAC",
    schools: [
      { name: "Akron", staffDirectoryUrl: "https://gozips.com/staff-directory" },
      { name: "Ball State", staffDirectoryUrl: "https://ballstatesports.com/staff-directory" },
      { name: "Bowling Green", staffDirectoryUrl: "https://bgsufalcons.com/staff-directory" },
      { name: "Buffalo", staffDirectoryUrl: "https://ubbulls.com/staff-directory" },
      { name: "Central Michigan", staffDirectoryUrl: "https://cmuchippewas.com/staff-directory" },
      { name: "Eastern Michigan", staffDirectoryUrl: "https://emueagles.com/staff-directory" },
      { name: "Kent State", staffDirectoryUrl: "https://kentstatesports.com/staff-directory" },
      { name: "Miami (OH)", staffDirectoryUrl: "https://miamiredhawks.com/staff-directory" },
      { name: "Northern Illinois", staffDirectoryUrl: "https://niuhuskies.com/staff-directory" },
      { name: "Ohio", staffDirectoryUrl: "https://ohiobobcats.com/staff-directory" },
      { name: "Toledo", staffDirectoryUrl: "https://utrockets.com/staff-directory" },
      { name: "Western Michigan", staffDirectoryUrl: "https://wmubroncos.com/staff-directory" },
    ],
  },
  {
    id: "CUSA",
    name: "Conference USA",
    shortName: "CUSA",
    schools: [
      { name: "FIU", staffDirectoryUrl: "https://fiusports.com/staff-directory" },
      { name: "Jacksonville State", staffDirectoryUrl: "https://jsugamecocksports.com/staff-directory" },
      { name: "Kennesaw State", staffDirectoryUrl: "https://ksuowls.com/staff-directory" },
      { name: "Louisiana Tech", staffDirectoryUrl: "https://latechsports.com/staff-directory" },
      { name: "Middle Tennessee", staffDirectoryUrl: "https://goblueraiders.com/staff-directory" },
      { name: "New Mexico State", staffDirectoryUrl: "https://nmstatesports.com/staff-directory" },
      { name: "Sam Houston", staffDirectoryUrl: "https://gobearkats.com/staff-directory" },
      { name: "UTEP", staffDirectoryUrl: "https://utepathletics.com/staff-directory" },
      { name: "Western Kentucky", staffDirectoryUrl: "https://wkusports.com/staff-directory" },
      { name: "Liberty", staffDirectoryUrl: "https://libertyflames.com/staff-directory" },
    ],
  },
  {
    id: "A10",
    name: "Atlantic 10 Conference",
    shortName: "A-10",
    schools: [
      { name: "Davidson", staffDirectoryUrl: "https://davidsonwildcats.com/staff-directory" },
      { name: "Dayton", staffDirectoryUrl: "https://daytonflyers.com/staff-directory" },
      { name: "Duquesne", staffDirectoryUrl: "https://goduquesne.com/staff-directory" },
      { name: "Fordham", staffDirectoryUrl: "https://fordhamsports.com/staff-directory" },
      { name: "George Mason", staffDirectoryUrl: "https://gomason.com/staff-directory" },
      { name: "George Washington", staffDirectoryUrl: "https://gwsports.com/staff-directory" },
      { name: "La Salle", staffDirectoryUrl: "https://goexplorers.com/staff-directory" },
      { name: "Loyola Chicago", staffDirectoryUrl: "https://loyolaramblers.com/staff-directory" },
      { name: "UMass", staffDirectoryUrl: "https://umassathletics.com/staff-directory" },
      { name: "Rhode Island", staffDirectoryUrl: "https://gorhody.com/staff-directory" },
      { name: "Richmond", staffDirectoryUrl: "https://richmondspiders.com/staff-directory" },
      { name: "Saint Louis", staffDirectoryUrl: "https://slubillikens.com/staff-directory" },
      { name: "St. Bonaventure", staffDirectoryUrl: "https://gobonnies.com/staff-directory" },
      { name: "Saint Joseph's", staffDirectoryUrl: "https://sjuhawks.com/staff-directory" },
      { name: "VCU", staffDirectoryUrl: "https://vcuathletics.com/staff-directory" },
    ],
  },
  {
    id: "WCC",
    name: "West Coast Conference",
    shortName: "WCC",
    schools: [
      { name: "Gonzaga", staffDirectoryUrl: "https://gozags.com/staff-directory" },
      { name: "Loyola Marymount", staffDirectoryUrl: "https://lmulions.com/staff-directory" },
      { name: "Pepperdine", staffDirectoryUrl: "https://pepperdinewaves.com/staff-directory" },
      { name: "Portland", staffDirectoryUrl: "https://portlandpilots.com/staff-directory" },
      { name: "Saint Mary's", staffDirectoryUrl: "https://smcgaels.com/staff-directory" },
      { name: "San Diego", staffDirectoryUrl: "https://usdtoreros.com/staff-directory" },
      { name: "San Francisco", staffDirectoryUrl: "https://usfdons.com/staff-directory" },
      { name: "Santa Clara", staffDirectoryUrl: "https://santaclarabroncos.com/staff-directory" },
      { name: "Pacific", staffDirectoryUrl: "https://pacifictigers.com/staff-directory" },
      { name: "Oregon State", staffDirectoryUrl: "https://osubeavers.com/staff-directory" },
    ],
  },
  {
    id: "MEAC",
    name: "Mid-Eastern Athletic Conference",
    shortName: "MEAC",
    schools: [
      { name: "Coppin State", staffDirectoryUrl: "https://coppinstatesports.com/staff-directory" },
      { name: "Delaware State", staffDirectoryUrl: "https://dsuhornets.com/staff-directory" },
      { name: "Howard", staffDirectoryUrl: "https://hubison.com/staff-directory" },
      { name: "Morgan State", staffDirectoryUrl: "https://maborathletics.com/staff-directory" },
      { name: "Norfolk State", staffDirectoryUrl: "https://nsuspartans.com/staff-directory" },
      { name: "NC Central", staffDirectoryUrl: "https://nccueaglepride.com/staff-directory" },
      { name: "SC State", staffDirectoryUrl: "https://scstatebulldogs.com/staff-directory" },
      { name: "Maryland Eastern Shore", staffDirectoryUrl: "https://umeshawks.com/staff-directory" },
    ],
  },
  {
    id: "SWAC",
    name: "Southwestern Athletic Conference",
    shortName: "SWAC",
    schools: [
      { name: "Alabama A&M", staffDirectoryUrl: "https://aamusports.com/staff-directory" },
      { name: "Alabama State", staffDirectoryUrl: "https://bamastatesports.com/staff-directory" },
      { name: "Alcorn State", staffDirectoryUrl: "https://alcornsports.com/staff-directory" },
      { name: "Bethune-Cookman", staffDirectoryUrl: "https://bcuathletics.com/staff-directory" },
      { name: "Florida A&M", staffDirectoryUrl: "https://famuathletics.com/staff-directory" },
      { name: "Grambling State", staffDirectoryUrl: "https://glostate.com/staff-directory" },
      { name: "Jackson State", staffDirectoryUrl: "https://gojsutigers.com/staff-directory" },
      { name: "Mississippi Valley State", staffDirectoryUrl: "https://mvsusports.com/staff-directory" },
      { name: "Prairie View A&M", staffDirectoryUrl: "https://pvpanthers.com/staff-directory" },
      { name: "Southern", staffDirectoryUrl: "https://gojagsports.com/staff-directory" },
      { name: "Texas Southern", staffDirectoryUrl: "https://tsusports.com/staff-directory" },
      { name: "Arkansas-Pine Bluff", staffDirectoryUrl: "https://uapblionsroar.com/staff-directory" },
    ],
  },
  {
    id: "Horizon",
    name: "Horizon League",
    shortName: "Horizon",
    schools: [
      { name: "Cleveland State", staffDirectoryUrl: "https://csuvikings.com/staff-directory" },
      { name: "Detroit Mercy", staffDirectoryUrl: "https://detroittitans.com/staff-directory" },
      { name: "Green Bay", staffDirectoryUrl: "https://greenbayphoenix.com/staff-directory" },
      { name: "IUPUI", staffDirectoryUrl: "https://iupuijags.com/staff-directory" },
      { name: "Milwaukee", staffDirectoryUrl: "https://mkepanthers.com/staff-directory" },
      { name: "Northern Kentucky", staffDirectoryUrl: "https://nkunorse.com/staff-directory" },
      { name: "Oakland", staffDirectoryUrl: "https://goldengrizzlies.com/staff-directory" },
      { name: "Purdue Fort Wayne", staffDirectoryUrl: "https://gomastodons.com/staff-directory" },
      { name: "Robert Morris", staffDirectoryUrl: "https://rmucolonials.com/staff-directory" },
      { name: "Wright State", staffDirectoryUrl: "https://wsuraiders.com/staff-directory" },
      { name: "Youngstown State", staffDirectoryUrl: "https://ysusports.com/staff-directory" },
    ],
  },
  {
    id: "MVC",
    name: "Missouri Valley Conference",
    shortName: "MVC",
    schools: [
      { name: "Belmont", staffDirectoryUrl: "https://belmontbruins.com/staff-directory" },
      { name: "Bradley", staffDirectoryUrl: "https://bradleybraves.com/staff-directory" },
      { name: "Drake", staffDirectoryUrl: "https://godrakebulldogs.com/staff-directory" },
      { name: "Evansville", staffDirectoryUrl: "https://gopurpleaces.com/staff-directory" },
      { name: "Illinois State", staffDirectoryUrl: "https://goredbirds.com/staff-directory" },
      { name: "Indiana State", staffDirectoryUrl: "https://gosycamores.com/staff-directory" },
      { name: "Missouri State", staffDirectoryUrl: "https://missouristatebears.com/staff-directory" },
      { name: "Murray State", staffDirectoryUrl: "https://goracers.com/staff-directory" },
      { name: "Northern Iowa", staffDirectoryUrl: "https://unipanthers.com/staff-directory" },
      { name: "Southern Illinois", staffDirectoryUrl: "https://siusalukis.com/staff-directory" },
      { name: "UIC", staffDirectoryUrl: "https://uicflames.com/staff-directory" },
      { name: "Valparaiso", staffDirectoryUrl: "https://valpoathletics.com/staff-directory" },
    ],
  },
  {
    id: "Summit",
    name: "Summit League",
    shortName: "Summit",
    schools: [
      { name: "Denver", staffDirectoryUrl: "https://denverpioneers.com/staff-directory" },
      { name: "Kansas City", staffDirectoryUrl: "https://umkcroos.com/staff-directory" },
      { name: "North Dakota", staffDirectoryUrl: "https://fightinghawks.com/staff-directory" },
      { name: "North Dakota State", staffDirectoryUrl: "https://gobison.com/staff-directory" },
      { name: "Omaha", staffDirectoryUrl: "https://omavs.com/staff-directory" },
      { name: "Oral Roberts", staffDirectoryUrl: "https://orugoldeneagles.com/staff-directory" },
      { name: "South Dakota", staffDirectoryUrl: "https://goyotes.com/staff-directory" },
      { name: "South Dakota State", staffDirectoryUrl: "https://gojacks.com/staff-directory" },
      { name: "St. Thomas", staffDirectoryUrl: "https://tommiesports.com/staff-directory" },
      { name: "Western Illinois", staffDirectoryUrl: "https://goleathernecks.com/staff-directory" },
    ],
  },
  {
    id: "BigSky",
    name: "Big Sky Conference",
    shortName: "Big Sky",
    schools: [
      { name: "Eastern Washington", staffDirectoryUrl: "https://goeags.com/staff-directory" },
      { name: "Idaho", staffDirectoryUrl: "https://govandals.com/staff-directory" },
      { name: "Idaho State", staffDirectoryUrl: "https://isubengals.com/staff-directory" },
      { name: "Montana", staffDirectoryUrl: "https://gogriz.com/staff-directory" },
      { name: "Montana State", staffDirectoryUrl: "https://msubobcats.com/staff-directory" },
      { name: "Northern Arizona", staffDirectoryUrl: "https://nauathletics.com/staff-directory" },
      { name: "Northern Colorado", staffDirectoryUrl: "https://uncbears.com/staff-directory" },
      { name: "Portland State", staffDirectoryUrl: "https://goviks.com/staff-directory" },
      { name: "Sacramento State", staffDirectoryUrl: "https://hornetsports.com/staff-directory" },
      { name: "UC Davis", staffDirectoryUrl: "https://ucdavisaggies.com/staff-directory" },
      { name: "Weber State", staffDirectoryUrl: "https://weberstatesports.com/staff-directory" },
      { name: "Cal Poly", staffDirectoryUrl: "https://gopoly.com/staff-directory" },
      { name: "Southern Utah", staffDirectoryUrl: "https://suutbirds.com/staff-directory" },
    ],
  },
];

export function getAllSchools(): NCASchool[] {
  return ncaaConferencesWithSchools.flatMap(conf => conf.schools);
}

export function getSchoolsByConference(conferenceId: string): NCASchool[] | undefined {
  return ncaaConferencesWithSchools.find(conf => conf.id === conferenceId)?.schools;
}
